image: "rust:jessie"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
    script:
    - rustc --version && cargo --version
    - cargo install cargo-travis
    - time cargo test --verbose --jobs 1 --release
    - cargo coverage
    cache:
        paths:
        - target/
        - cargo/

