image: "rust:stretch"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
    script:
    - rustc --version && cargo --version
    - apt-get update && apt-get install -y cmake libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev
    - cargo install cargo-travis
    - time cargo test --verbose --jobs 1 --release
    - cargo coverage
    cache:
        paths:
        - target/
        - cargo/

