image: "rust:stretch"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
    script:
    - rustc --version && cargo --version
    - time cargo test --verbose --release
    cache:
        paths:
        - target/
        - cargo/

